In [35]:
import scanpy as sc
import pandas as pd
import scipy.io
import anndata
from scipy.sparse import csr_matrix
import os
import scanpy as sc
import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
import re

In [38]:
adata1=sc.read_h5ad("/storage2/liuxiaodongLab/fanxueying/liu-lab_projects/XueyingFan/Ali_oss/hypoblast_100_samples_human_aligned_only_counts.h5ad")

In [39]:
adata1

AnnData object with n_obs × n_vars = 1207197 × 38606
    obs: 'condition', 'cell_name_in_hg38_mm10', 'batch'

In [40]:
adata1 = adata1[adata1.obs['condition'] != 'H163'].copy()

In [41]:
adata2=sc.read_h5ad("/storage2/liuxiaodongLab/fanxueying/liu-lab_projects/XueyingFan/Hypoblast/code/20260310_hypo_batch2/hypo_human_aligned_only_82samples.h5ad")

In [42]:
adata3=sc.read_h5ad("/storage2/liuxiaodongLab/fanxueying/liu-lab_projects/XueyingFan/Hypoblast/code/20260311_hypo_batch2_full/hypo_human_aligned_only_4samples.h5ad")

In [43]:
adata4=sc.concat([adata2,adata3],join='outer',label='seq')

In [44]:
import re

# 方法1：使用正则表达式匹配最后一个-H后面的数字
def extract_condition(barcode):
    # 匹配最后一个-H后面的H加上数字
    match = re.search(r'-([H][0-9]+)$', str(barcode))
    if match:
        return match.group(1)
    else:
        # 尝试其他模式
        match = re.search(r'(H[0-9]+)$', str(barcode))
        return match.group(1) if match else None

adata4.obs['condition'] = adata4.obs.index.map(extract_condition)

# 查看结果
print(adata4.obs[['condition']].head(10))

                                                   condition
GCTAAGTACTGTAACCACCG;TCAACGAACCCGAGTTCAGC;TCGGC...      H245
CGACGTTCCTAATACTCGAT;GAACTGCTCCCACCTAGGAA;TTGTA...      H245
CAACATCGCGAAGTTGGAGG-H245                               H245
ATCATTCAGCGCGGTGCAGA;CACAAGGTCTGTAATCTTCA;CTTAC...      H245
AACACTCTCCCATCTATATA;ACTTCAACACGAAGGCAAGC;CTTCA...      H245
AGTTGTCGAACCACAGGTAT-H245                               H245
ATAAGTCATGCGCGAGGACC;GACTGTTCCTCATCAACGTA;TGGTT...      H245
ACCAATCTAACTTCGACCAA;GACGCGGTTGTCTTACAACG;TCGTA...      H245
AAGATGGCCTCATCGGCATG-H245                               H245
CGGTCGAACCGTCTCACAGT-H245                               H245

In [10]:
print(adata4.obs.index[:10])

Index(['GCTAAGTACTGTAACCACCG;TCAACGAACCCGAGTTCAGC;TCGGCGCTGCGCTCGGTATG-H245',
       'CGACGTTCCTAATACTCGAT;GAACTGCTCCCACCTAGGAA;TTGTACACGTATATCCGAAT-H245',
       'CAACATCGCGAAGTTGGAGG-H245',
       'ATCATTCAGCGCGGTGCAGA;CACAAGGTCTGTAATCTTCA;CTTACCGGTGGTTGTCTGAC;GTGGCAGGTGGAGGCAAGTC-H245',
       'AACACTCTCCCATCTATATA;ACTTCAACACGAAGGCAAGC;CTTCAATAATTCCGACTTAA;TCTACAGTGGACATTCCGTT-H245',
       'AGTTGTCGAACCACAGGTAT-H245',
       'ATAAGTCATGCGCGAGGACC;GACTGTTCCTCATCAACGTA;TGGTTAGGCATGATGATTAA;TTACTGCTGAGCGCGTACGC-H245',
       'ACCAATCTAACTTCGACCAA;GACGCGGTTGTCTTACAACG;TCGTAGTCGTGGCAGACCTA-H245',
       'AAGATGGCCTCATCGGCATG-H245', 'CGGTCGAACCGTCTCACAGT-H245'],
      dtype='object')

In [45]:
adata2=adata4

In [46]:
adata2.obs['batch']="batch2"

In [47]:
adata=sc.concat([adata1,adata2],join='outer',label='seq')

In [48]:
adata.obs

,condition,cell_name_in_hg38_mm10,batch,seq
CACCGTGTGTTAAGGAGAAG;GCTAAGTACTCCTATTGGTG-H4,H4,CELL12915_N2,seq_7,0
CGATTGATAAGCTCACCTCC-H4,H4,CELL42201_N1,seq_7,0
GGCAGGAGCTGTCAGGTCGT;GTGACATACATTCAGCAACT-H4,H4,CELL23261_N2,seq_7,0
AACCTGGTGACTTGTCTAGT;GAACCGCCTCTGAGTCTAGT;GACAGTTAGGCTTCTTCGTA;TATGCCTGATCACAAGGTCT-H4,H4,CELL350_N4,seq_7,0
ACCGCGGTAACAGATTCAAC;AGTCGTCCTAGATGAGAGGT-H4,H4,CELL4761_N2,seq_7,0
...,...,...,...,...
CTACTACGCGATTACATAAT-H221,H221,NaN,batch2,1
GGCCTGCACAACAGTTCATT;TGCAACCGGATCGAACGCCA-H221,H221,NaN,batch2,1
AATGGAATACCCTGCGAACA;GCGACAGTGTGTGAAGTCGG-H221,H221,NaN,batch2,1
CCGATTCCAACTCACCTAAG;CGGTAGACACGCACATAGTA;CTGGCAACATGCCGTACGGT;GCCAGGTTGCGGCTCCGCTG;GTCCGTCACACAAGCTGAAG;GTCTTCGGCTTGAAGGAAGG;TATTCATATATTATGGCCAA;TTCTATCAGCCCTGATATAG-H221,H221,NaN,batch2,1
GCGTAAGTAGGGCTCCGCTG-H221,H221,NaN,batch2,1

In [49]:
condition_info = {
    'control': {'time': 7, 'group': 'day7_ctl'},
    'H4': {'time': 20, 'group': 'day20_ctl'},
    'H5': {'time': 20, 'group': 'Act'},
    'H6': {'time': 20, 'group': 'A83'},
    'H7': {'time': 20, 'group': 'BMP4'},
    'H8': {'time': 20, 'group': 'LDN'},
    'H9': {'time': 20, 'group': 'CHIR'},
    'H10': {'time': 20, 'group': 'XAV'},
    'H11': {'time': 20, 'group': 'FGF4'},
    'H13': {'time': 20, 'group': 'PDG'},
    'H14': {'time': 20, 'group': 'LIF'},
    'H15': {'time': 20, 'group': 'Act_BMP4'},
    'H16': {'time': 20, 'group': 'Act_LDN'},
    'H17': {'time': 20, 'group': 'Act_CHIR'},
    'H18': {'time': 20, 'group': 'Act_XAV'},
    'H19': {'time': 20, 'group': 'Act_FGF4'},
    'H21': {'time': 20, 'group': 'Act_PDG'},
    'H22': {'time': 20, 'group': 'Act_LIF'},
    'H23': {'time': 20, 'group': 'A83_BMP4'},
    'H24': {'time': 20, 'group': 'A83_LDN'},
    'H25': {'time': 20, 'group': 'A83_CHIR'},
    'H26': {'time': 20, 'group': 'A83_XAV'},
    'H27': {'time': 20, 'group': 'A83_FGF4'},
    'H29': {'time': 20, 'group': 'A83_PDG'},
    'H30': {'time': 20, 'group': 'A83_LIF'},
    'H31': {'time': 20, 'group': 'BMP4_CHIR'},
    'H32': {'time': 20, 'group': 'BMP4_XAV'},
    'H33': {'time': 20, 'group': 'BMP4_FGF4'},
    'H35': {'time': 20, 'group': 'BMP4_PDG'},
    'H36': {'time': 20, 'group': 'BMP4_LIF'},
    'H37': {'time': 20, 'group': 'LDN_CHIR'},
    'H38': {'time': 20, 'group': 'LDN_XAV'},
    'H39': {'time': 20, 'group': 'LDN_FGF4'},
    'H41': {'time': 20, 'group': 'LDN_PDG'},
    'H42': {'time': 20, 'group': 'LDN_LIF'},
    'H43': {'time': 20, 'group': 'CHIR_FGF4'},
    'H45': {'time': 20, 'group': 'CHIR_PDG'},
    'H46': {'time': 20, 'group': 'CHIR_LIF'},
    'H47': {'time': 20, 'group': 'XAV_FGF4'},
    'H49': {'time': 20, 'group': 'XAV_PDG'},
    'H50': {'time': 20, 'group': 'XAV_LIF'},
    'H51': {'time': 20, 'group': 'FGF4_PDG'},
    'H52': {'time': 20, 'group': 'FGF4_LIF'},
    'H55': {'time': 20, 'group': 'PDG_LIF'},
    'H56': {'time': 20, 'group': 'Act_BMP4_CHIR'},
    'H57': {'time': 20, 'group': 'Act_BMP4_XAV'},
    'H62': {'time': 20, 'group': 'Act_LDN_CHIR'},
    'H63': {'time': 20, 'group': 'Act_LDN_XAV'},
    'H64': {'time': 20, 'group': 'Act_LDN_FGF4'},
    'H68': {'time': 20, 'group': 'Act_CHIR_FGF4'},
    'H70': {'time': 20, 'group': 'Act_CHIR_PDG'},
    'H71': {'time': 20, 'group': 'Act_CHIR_LIF'},
    'H74': {'time': 20, 'group': 'Act_XAV_PDG'},
    'H75': {'time': 20, 'group': 'Act_XAV_LIF'},
    'H81': {'time': 20, 'group': 'A83_BMP4_CHIR'},
    'H82': {'time': 20, 'group': 'A83_BMP4_XAV'},
    'H83': {'time': 20, 'group': 'A83_BMP4_PDG'},
    'H85': {'time': 20, 'group': 'A83_BMP4_PDG'},
    'H86': {'time': 20, 'group': 'A83_BMP4_LIF'},
    'H87': {'time': 20, 'group': 'A83_LDN_CHIR'},
    'H91': {'time': 20, 'group': 'A83_LDN_PDG'},
    'H92': {'time': 20, 'group': 'A83_LDN_LIF'},
    'H93': {'time': 20, 'group': 'A83_CHIR_FGF4'},
    'H95': {'time': 20, 'group': 'A83_CHIR_PDG'},
    'H96': {'time': 20, 'group': 'A83_CHIR_LIF'},
    'H97': {'time': 20, 'group': 'A83_XAV_FGF4'},
    'H99': {'time': 20, 'group': 'A83_XAV_PDG'},
    'H100': {'time': 20, 'group': 'A83_XAV_LIF'},
    'H109': {'time': 20, 'group': 'BMP4_CHIR_LIF'},
    'H110': {'time': 20, 'group': 'BMP4_XAV_FGF4'},
    'H112': {'time': 20, 'group': 'BMP4_XAV_PDG'},
    'H113': {'time': 20, 'group': 'BMP4_XAV_LIF'},
    'H114': {'time': 20, 'group': 'BMP4_FGF4_PDG'},
    'H115': {'time': 20, 'group': 'BMP4_FGF4_LIF'},
    'H118': {'time': 20, 'group': 'BMP4_PDG_LIF'},
    'H119': {'time': 20, 'group': 'LDN_CHIR_FGF4'},
    'H126': {'time': 20, 'group': 'LDN_XAV_LIF'},
    'H127': {'time': 20, 'group': 'LDN_FGF4_PDG'},
    'H132': {'time': 20, 'group': 'CHIR_FGF4_PDG'},
    'H133': {'time': 20, 'group': 'CHIR_FGF4_LIF'},
    'H136': {'time': 20, 'group': 'CHIR_PDG_LIF'},
    'H137': {'time': 20, 'group': 'XAV_FGF4_PDG'},
    'H138': {'time': 20, 'group': 'XAV_FGF4_LIF'},
    'H141': {'time': 20, 'group': 'XAV_PDG_LIF'},
    'H142': {'time': 20, 'group': 'FGF4_PDG_LIF'},
    'H149': {'time': 20, 'group': 'A83_BMP4_PDG_LIF'},
    'H159': {'time': 20, 'group': 'Act_BMP4_CHIR_FGF4_PDG_LIF'},
    'H160': {'time': 20, 'group': 'Act_BMP4_XAV_FGF4_PDG_LIF'},
    'H161': {'time': 20, 'group': 'Act_LDN_CHIR_FGF4_PDG_LIF'},
    'H162': {'time': 20, 'group': 'Act_LDN_XAV_FGF4_PDG_LIF'},
    'H163': {'time': 20, 'group': 'A83_BMP4_CHIR_FGF4_PDG_LIF'},
    'H164': {'time': 20, 'group': 'A83_BMP4_XAV_FGF4_PDG_LIF'},
    'H165': {'time': 20, 'group': 'A83_LDN_CHIR_FGF4_PDG_LIF'},
    'H166': {'time': 20, 'group': 'A83_LDN_XAV_FGF4_PDG_LIF'},
    'H167': {'time': 20, 'group': 'BMP4_XAV_FGF4_PDG'},
    'H168': {'time': 20, 'group': 'A83_CHIR_FGF4_LIF'},
    'H169': {'time': 20, 'group': 'Act_LDN_CHIR_PDG'},
    'H170': {'time': 20, 'group': 'A83_BMP4_XAV_PDG_LIF'},
    'H171': {'time': 20, 'group': 'A83_BMP4_CHIR_FGF4_LIF'},
    'H172': {'time': 20, 'group': 'Act_LDN_CHIR_FGF4_PDG'},
    'H245': {'time': 7, 'group': 'day7_ctl'},
    'H246': {'time': 20, 'group': 'day20_ctl'},
    'H12': {'time': 20, 'group': 'PD0'},
    'H20': {'time': 20, 'group': 'PD0_Act'},
    'H28': {'time': 20, 'group': 'PD0_A83'},
    'H44': {'time': 20, 'group': 'PD0_CHIR'},
    'H48': {'time': 20, 'group': 'PD0_XAV'},
    'H58': {'time': 20, 'group': 'Act_BMP4_FGF4'},
    'H60': {'time': 20, 'group': 'Act_BMP4_PDG'},
    'H61': {'time': 20, 'group': 'Act_BMP4_LIF'},
    'H66': {'time': 20, 'group': 'Act_LDN_PDG'},
    'H67': {'time': 20, 'group': 'Act_LDN_LIF'},
    'H72': {'time': 20, 'group': 'Act_XAV_FGF4'},
    'H76': {'time': 20, 'group': 'Act_FGF4_PDG'},
    'H77': {'time': 20, 'group': 'Act_FGF4_LIF'},
    'H80': {'time': 20, 'group': 'Act_PDG_LIF'},
    'H88': {'time': 20, 'group': 'A83_LDN_XAV'},
    'H89': {'time': 20, 'group': 'A83_LDN_FGF4'},
    'H101': {'time': 20, 'group': 'A83_FGF4_PDG'},
    'H102': {'time': 20, 'group': 'A83_FGF4_LIF'},
    'H105': {'time': 20, 'group': 'A83_PDG_LIF'},
    'H106': {'time': 20, 'group': 'BMP4_CHIR_FGF4'},
    'H108': {'time': 20, 'group': 'BMP4_CHIR_PDG'},
    'H121': {'time': 20, 'group': 'LDN_CHIR_PDG'},
    'H122': {'time': 20, 'group': 'LDN_CHIR_LIF'},
    'H123': {'time': 20, 'group': 'LDN_XAV_FGF4'},
    'H125': {'time': 20, 'group': 'LDN_XAV_PDG'},
    'H128': {'time': 20, 'group': 'LDN_FGF4_LIF'},
    'H131': {'time': 20, 'group': 'LDN_PDG_LIF'},
    'H173': {'time': 20, 'group': 'FGF2'},
    'H174': {'time': 20, 'group': 'IL6'},
    'H175': {'time': 20, 'group': 'Go6983'},
    'H176': {'time': 20, 'group': 'CGP77675'},
    'H177': {'time': 20, 'group': 'Y27632'},
    'H178': {'time': 20, 'group': 'VPA'},
    'H180': {'time': 20, 'group': 'VitC'},
    'H181': {'time': 20, 'group': 'RA'},
    'H182': {'time': 20, 'group': 'Forskolin'},
    'H183': {'time': 20, 'group': 'IGF1'},
    'H185': {'time': 20, 'group': 'EPZ'},
    'H186': {'time': 20, 'group': 'WH4'},
    'H188': {'time': 20, 'group': 'Go6983_Act'},
    'H189': {'time': 20, 'group': 'CGP_FGF4'},
    'H190': {'time': 20, 'group': 'CGP_CHIR'},
    'H191': {'time': 20, 'group': 'Y27632_XAV'},
    'H192': {'time': 20, 'group': 'Y27632_LIF'},
    'H193': {'time': 20, 'group': 'VPA_BMP4'},
    'H194': {'time': 20, 'group': 'VPA_CHIR'},
    'H197': {'time': 20, 'group': 'VitC_PDG'},
    'H198': {'time': 20, 'group': 'VitC_A83'},
    'H199': {'time': 20, 'group': 'RA_Act'},
    'H200': {'time': 20, 'group': 'RA_BMP4'},
    'H201': {'time': 20, 'group': 'Forskolin_A83'},
    'H202': {'time': 20, 'group': 'IGF1_BMP4'},
    'H203': {'time': 20, 'group': 'IGF1_CHIR'},
    'H204': {'time': 20, 'group': 'DZNeP_LDN'},
    'H205': {'time': 20, 'group': 'DZNeP_CHIR'},
    'H206': {'time': 20, 'group': 'EPZ_CHIR'},
    'H207': {'time': 20, 'group': 'EPZ_FGF4'},
    'H208': {'time': 20, 'group': 'WH4_XAV'},
    'H209': {'time': 20, 'group': 'WH4_Act'},
    'H210': {'time': 20, 'group': 'SP_FGF4'},
    'H212': {'time': 20, 'group': 'FGF2_Go6983'},
    'H213': {'time': 20, 'group': 'FGF2_IL6'},
    'H214': {'time': 20, 'group': 'IL6_WH4'},
    'H215': {'time': 20, 'group': 'Go6983_Forskolin'},
    'H216': {'time': 20, 'group': 'DZNeP_EPZ'},
    'H218': {'time': 20, 'group': 'Go6983_DZNeP'},
    'H221': {'time': 20, 'group': 'Forskolin_VPA'},
    'H223': {'time': 20, 'group': 'CGP_EPZ'},
    'H224': {'time': 20, 'group': 'IGF1_Go6983'},
    'H225': {'time': 20, 'group': 'PD0_CHIR_LIF_Go6983'},
    'H226': {'time': 20, 'group': 'PD0_XAV_LIF_Go6983'},
    'H227': {'time': 20, 'group': 'PD0_XAV_Go6983_CGP_Act_LIF'},
    'H228': {'time': 20, 'group': 'PD0_XAV_Go6983_CGP_LIF'},
    'H229': {'time': 20, 'group': 'PD0_XAV_DZN_VPA_Act_LIF_VitC'},
    'H230': {'time': 20, 'group': 'PD0_XAV_DZN_VPA_LIF_VitC'},
    'H231': {'time': 20, 'group': 'CHIR_VPA_EPZ_RA_VitC'},
    'H237': {'time': 20, 'group': 'PD0_A83_BMP4'},
    'H238': {'time': 20, 'group': 'PD0_A83_BMP4_VPA'},
    'H239': {'time': 20, 'group': 'PD0_A83_BMP4_VPA_CHIR'},
    'H240': {'time': 20, 'group': 'FGF2_Act_XAV'},
    'H241': {'time': 20, 'group': 'Act_IGF1_FGF2'},
    'H242': {'time': 20, 'group': 'FGF2_Act_IGF1_XAV'},
    'H243': {'time': 20, 'group': 'FGF2_Act_XAV_SP_VitC'},
    'H244': {'time': 20, 'group': 'FGF2_Act_VitC_Forskolin'}
}

# 从 condition 列提取信息添加新列
adata.obs['time'] = adata.obs['condition'].map(lambda x: condition_info[x]['time'])
adata.obs['group'] = adata.obs['condition'].map(lambda x: condition_info[x]['group'])

# 验证添加的列
print(adata.obs[['condition', 'time', 'group']].head())

                                                   condition  time      group
CACCGTGTGTTAAGGAGAAG;GCTAAGTACTCCTATTGGTG-H4              H4    20  day20_ctl
CGATTGATAAGCTCACCTCC-H4                                   H4    20  day20_ctl
GGCAGGAGCTGTCAGGTCGT;GTGACATACATTCAGCAACT-H4              H4    20  day20_ctl
AACCTGGTGACTTGTCTAGT;GAACCGCCTCTGAGTCTAGT;GACAG...        H4    20  day20_ctl
ACCGCGGTAACAGATTCAAC;AGTCGTCCTAGATGAGAGGT-H4              H4    20  day20_ctl

In [50]:
import scanpy as sc
import numpy as np

def calculate_qc_metrics(adata):
    """
    计算质控指标：线粒体基因比例、核糖体基因比例等
    """
    print("计算质控指标...")
    
    # 确保有基因注释信息
    if 'gene_name' not in adata.var.columns and adata.var.index.name == 'gene_ids':
        adata.var.index = adata.var.index.astype(str)
    
    # 识别线粒体基因（根据不同物种调整）
    # 人类/小鼠：以mt-或MT-开头
    # 可以根据你的物种调整
    if adata.var.index.dtype == 'object':
        # 尝试不同格式的线粒体基因标识
        mt_patterns = ['^MT-', '^mt-', '_MT', '_mt', 'MT.', 'mt.']
        
        for pattern in mt_patterns:
            mt_genes = adata.var.index.str.contains(pattern, case=False, regex=True)
            if mt_genes.sum() > 0:
                print(f"找到 {mt_genes.sum()} 个线粒体基因 (使用模式: {pattern})")
                break
        else:
            # 如果没有找到，尝试基因名字段
            if 'gene_name' in adata.var.columns:
                for pattern in mt_patterns:
                    mt_genes = adata.var['gene_name'].str.contains(pattern, case=False, regex=True, na=False)
                    if mt_genes.sum() > 0:
                        print(f"找到 {mt_genes.sum()} 个线粒体基因 (使用模式: {pattern})")
                        break
                else:
                    mt_genes = np.zeros(adata.n_vars, dtype=bool)
                    print("警告: 未找到线粒体基因，请检查基因注释")
    else:
        mt_genes = np.zeros(adata.n_vars, dtype=bool)
    
    # 识别核糖体基因
    ribosomal_patterns = ['^RP[LS]', '^rp[ls]', 'Rps', 'Rpl']
    ribo_genes = np.zeros(adata.n_vars, dtype=bool)
    
    for pattern in ribosomal_patterns:
        if adata.var.index.dtype == 'object':
            ribo_genes = ribo_genes | adata.var.index.str.contains(pattern, case=False, regex=True)
        if 'gene_name' in adata.var.columns:
            ribo_genes = ribo_genes | adata.var['gene_name'].str.contains(pattern, case=False, regex=True, na=False)
    
    # 计算基本QC指标
    print("计算每个细胞的基因数和UMI数...")
    adata.var['mt'] = mt_genes
    adata.var['ribo'] = ribo_genes
    
    # 计算各种QC指标
    sc.pp.calculate_qc_metrics(
        adata, 
        qc_vars=['mt', 'ribo'], 
        percent_top=None, 
        log1p=False, 
        inplace=True
    )
    
    print(f"计算完成:")
    print(f"  - 总细胞数: {adata.n_obs}")
    print(f"  - 总基因数: {adata.n_vars}")
    print(f"  - 线粒体基因比例范围: {adata.obs['pct_counts_mt'].min():.2f}% - {adata.obs['pct_counts_mt'].max():.2f}%")
    print(f"  - 核糖体基因比例范围: {adata.obs['pct_counts_ribo'].min():.2f}% - {adata.obs['pct_counts_ribo'].max():.2f}%")
    print(f"  - 每个细胞检测到的基因数范围: {adata.obs['n_genes_by_counts'].min()} - {adata.obs['n_genes_by_counts'].max()}")
    print(f"  - 每个细胞的UMI总数范围: {adata.obs['total_counts'].min()} - {adata.obs['total_counts'].max()}")
    
    return adata

def preprocess_and_qc_analysis(adata_combined, filter_params):
    """
    对合并的adata进行质控和分析
    """
    
    print("="*60)
    print("开始质控分析流程")
    print("="*60)
    
    # 步骤1: 计算质控指标
    initial_shape = adata_combined.shape
    print(f"初始数据形状: {initial_shape}")
    
    adata_combined = calculate_qc_metrics(adata_combined)
    
    # 步骤2: 保存原始counts
    print("\n保存原始counts数据...")
    adata_combined.layers["counts"] = adata_combined.X.copy()
    
    # 步骤3: 质控过滤
    print("\n进行质控过滤...")
    print(f"使用过滤参数: {filter_params}")
    
    initial_cells = adata_combined.n_obs
    
    # 创建过滤掩码
    filter_mask = (
        (adata_combined.obs['n_genes_by_counts'] > filter_params['min_genes']) & 
        (adata_combined.obs['n_genes_by_counts'] < filter_params['max_genes']) & 
        (adata_combined.obs['total_counts'] > filter_params['min_counts']) & 
        (adata_combined.obs['total_counts'] < filter_params['max_counts']) & 
        (adata_combined.obs['pct_counts_mt'] < filter_params['max_mt'])
    )
    
    # 如果是合并的数据，可能有不同样本，可以分别查看
    if 'condition' in adata_combined.obs.columns:
        print("\n各样本过滤前细胞数:")
        print(adata_combined.obs['condition'].value_counts())
    
    # 应用过滤
    adata_filtered = adata_combined[filter_mask].copy()
    
    # 移除的细胞统计
    removed_cells = initial_cells - adata_filtered.n_obs
    removal_rate = (removed_cells / initial_cells) * 100
    
    print(f"\n质控过滤结果:")
    print(f"  - 过滤前: {initial_cells} 个细胞")
    print(f"  - 过滤后: {adata_filtered.n_obs} 个细胞")
    print(f"  - 移除: {removed_cells} 个细胞 ({removal_rate:.1f}%)")
    
    if removed_cells > 0:
        # 分析被移除细胞的原因
        removed_adata = adata_combined[~filter_mask]
        
        reasons = {
            '低基因数': (removed_adata.obs['n_genes_by_counts'] <= filter_params['min_genes']).sum(),
            '高基因数': (removed_adata.obs['n_genes_by_counts'] >= filter_params['max_genes']).sum(),
            '低UMI数': (removed_adata.obs['total_counts'] <= filter_params['min_counts']).sum(),
            '高UMI数': (removed_adata.obs['total_counts'] >= filter_params['max_counts']).sum(),
            '高线粒体比例': (removed_adata.obs['pct_counts_mt'] >= filter_params['max_mt']).sum()
        }
        
        print(f"\n细胞被移除的主要原因:")
        for reason, count in reasons.items():
            if count > 0:
                percent = (count / removed_cells) * 100
                print(f"  - {reason}: {count} 个细胞 ({percent:.1f}%)")
    
    # 步骤4: 过滤基因和细胞
    print("\n进行基因和细胞过滤...")
    
    # 过滤低表达基因
    initial_genes = adata_filtered.n_vars
    sc.pp.filter_genes(adata_filtered, min_cells=3)
    after_gene_filter = adata_filtered.n_vars
    removed_genes = initial_genes - after_gene_filter
    print(f"  基因过滤: {initial_genes} -> {after_gene_filter} (移除 {removed_genes} 个基因)")
    
    # 过滤低表达细胞（可选，因为已经在质控中过滤过）
    initial_cells = adata_filtered.n_obs
    sc.pp.filter_cells(adata_filtered, min_genes=200)
    after_cell_filter = adata_filtered.n_obs
    removed_cells_extra = initial_cells - after_cell_filter
    if removed_cells_extra > 0:
        print(f"  额外细胞过滤: {initial_cells} -> {after_cell_filter} (移除 {removed_cells_extra} 个细胞)")
    
    # # 步骤5: 双细胞检测（如果样本量足够大）
    # if adata_filtered.n_obs > 1000:
    #     print("\n运行Scrublet检测双细胞...")
    #     try:
    #         sc.external.pp.scrublet(adata_filtered)
            
    #         if 'predicted_doublet' in adata_filtered.obs.columns:
    #             initial_cells = adata_filtered.n_obs
    #             doublet_count = adata_filtered.obs['predicted_doublet'].sum()
    #             doublet_rate = (doublet_count / initial_cells) * 100
                
    #             print(f"  检测到 {doublet_count} 个双细胞 ({doublet_rate:.2f}%)")
                
    #             # 根据双细胞比例决定是否移除
    #             if doublet_rate > 1.0:  # 如果双细胞率超过1%
    #                 adata_filtered = adata_filtered[~adata_filtered.obs['predicted_doublet']].copy()
    #                 removed_doublets = initial_cells - adata_filtered.n_obs
    #                 print(f"  双细胞移除: {initial_cells} -> {adata_filtered.n_obs} (移除 {removed_doublets} 个双细胞)")
    #             else:
    #                 print(f"  双细胞率较低 ({doublet_rate:.2f}%)，保留所有细胞")
    #     except Exception as e:
    #         print(f"  Scrublet检测失败: {e}")
    # else:
    #     print(f"\n跳过双细胞检测 (细胞数 {adata_filtered.n_obs} < 1000)")
    
    # 步骤6: 数据标准化和后续分析
    print("\n进行数据标准化...")
    
    # 确保使用原始counts进行标准化
    if 'counts' in adata_filtered.layers:
        print("  使用counts层进行标准化")
        adata_filtered.X = adata_filtered.layers['counts'].copy()
    else:
        print("  警告: 未找到counts层，使用当前X矩阵")
    
    # 标准化
    sc.pp.normalize_total(adata_filtered, target_sum=10000)
    sc.pp.log1p(adata_filtered)
    
    # 保存log转换后的数据
    adata_filtered.layers["logcounts"] = adata_filtered.X.copy()
    
    # 步骤7: 高变基因选择
    print("\n选择高变基因...")
    
    # 如果有批次信息，使用批次校正选择高变基因
    if 'condition' in adata_filtered.obs.columns:
        sc.pp.highly_variable_genes(
            adata_filtered, 
            n_top_genes=2000, 
            batch_key='condition'
        )
    else:
        sc.pp.highly_variable_genes(
            adata_filtered, 
            n_top_genes=2000,
        )
    
    sc.tl.pca(adata_filtered)
    
    # 计算邻居图
    print("  计算邻居图...")
    sc.pp.neighbors(adata_filtered, n_pcs=30)
    
    # UMAP降维
    print("  进行UMAP降维...")
    sc.tl.umap(adata_filtered)
    
    # Leiden聚类
    print("  进行Leiden聚类...")
    sc.tl.leiden(adata_filtered)
    return adata_filtered

# 使用示例
def main():
    """
    主函数：加载数据并运行质控分析
    """
    
    # 2. 设置质控参数（根据你的数据调整）
    filter_params = {
        'min_genes': 500,      
        'max_genes': 12000,     
        'min_counts': 500,     # 最小UMI数
        'max_counts': 150000,   # 最大UMI数
        'max_mt': 10          # 最大线粒体基因百分比
    }
    
    # 3. 运行质控分析
    adata_qc = preprocess_and_qc_analysis(adata, filter_params)
    
    # 4. 可视化质控结果
    #visualize_qc(adata_qc, save_dir="./qc_results")
    
    # 5. 保存质控后的数据
    #adata_qc.write_h5ad("adata_qc_filtered.h5ad")
    
    #print("质控完成！数据已保存为 adata_qc_filtered.h5ad")

In [51]:
import pandas as pd
import numpy as np

# 创建condition到batch的映射字典
condition_to_batch = {
    # seq2_1
    'H245': 'seq2_1',
    
    # seq2_2
    'H246': 'seq2_2', 'H48': 'seq2_2', 'H44': 'seq2_2', 'H28': 'seq2_2', 
    'H244': 'seq2_2', 'H242': 'seq2_2', 'H243': 'seq2_2', 'H20': 'seq2_2', 
    'H12': 'seq2_2', 'H186': 'seq2_2', 'H185': 'seq2_2',
    
    # seq2_3
    'H192': 'seq2_3', 'H241': 'seq2_3', 'H240': 'seq2_3', 'H239': 'seq2_3', 
    'H238': 'seq2_3', 'H193': 'seq2_3', 'H191': 'seq2_3', 'H190': 'seq2_3', 
    'H189': 'seq2_3', 'H188': 'seq2_3',
    
    # seq2_4
    'H89': 'seq2_4', 'H208': 'seq2_4', 'H212': 'seq2_4', 'H105': 'seq2_4', 
    'H80': 'seq2_4', 'H102': 'seq2_4', 'H210': 'seq2_4', 'H207': 'seq2_4', 
    'H209': 'seq2_4', 'H88': 'seq2_4', 'H108': 'seq2_4', 'H204': 'seq2_4', 
    'H206': 'seq2_4', 'H205': 'seq2_4', 'H106': 'seq2_4', 'H101': 'seq2_4',
    
    # seq2_5
    'H58': 'seq2_5', 'H60': 'seq2_5', 'H61': 'seq2_5', 'H66': 'seq2_5', 
    'H67': 'seq2_5', 'H72': 'seq2_5', 'H76': 'seq2_5', 'H77': 'seq2_5', 
    'H194': 'seq2_5', 'H197': 'seq2_5', 'H198': 'seq2_5', 'H199': 'seq2_5', 
    'H200': 'seq2_5', 'H201': 'seq2_5', 'H202': 'seq2_5', 'H203': 'seq2_5',
    
    # seq2_6
    'H121': 'seq2_6', 'H122': 'seq2_6', 'H123': 'seq2_6', 'H125': 'seq2_6', 
    'H128': 'seq2_6', 'H131': 'seq2_6', 'H173': 'seq2_6', 'H174': 'seq2_6', 
    'H213': 'seq2_6', 'H214': 'seq2_6', 'H215': 'seq2_6', 'H216': 'seq2_6', 
    'H218': 'seq2_6', 'H221': 'seq2_6', 'H223': 'seq2_6', 'H224': 'seq2_6',
    
    # seq2_7
    'H183': 'seq2_7', 'H182': 'seq2_7', 'H181': 'seq2_7', 'H180': 'seq2_7', 'H178': 'seq2_7',
    'H177': 'seq2_7', 'H176': 'seq2_7', 'H175': 'seq2_7', 'H228': 'seq2_7', 
    'H227': 'seq2_7', 'H226': 'seq2_7', 'H225': 'seq2_7', 'H237': 'seq2_7', 
    'H231': 'seq2_7', 'H230': 'seq2_7', 'H229': 'seq2_7'
}

# 获取所有新的batch名称
new_batches = set(condition_to_batch.values())
print(f"要确保存在的batch类别：{new_batches}")

# 方法1：如果batch列不是category类型，先获取当前唯一值
current_values = set(adata.obs['batch'].unique())
print(f"当前的batch值：{current_values}")

# 合并所有类别（当前值 + 新类别）
all_categories = sorted(set(current_values) | new_batches)
print(f"\n合并后的所有类别：{all_categories}")

# 将batch列转换为category类型，并设置所有类别
adata.obs['batch'] = pd.Categorical(adata.obs['batch'], categories=all_categories)

# 验证新类别已添加
print("\n重新设置类别后的batch类别：")
print(adata.obs['batch'].cat.categories)

# 创建mask：标记原本是batch2且condition在映射字典中的细胞
mask_batch2 = (adata.obs['batch'] == 'batch2') & (adata.obs['condition'].isin(condition_to_batch.keys()))

print(f"\n需要修改的细胞数量：{mask_batch2.sum()}")

# 修改这部分细胞的batch
adata.obs.loc[mask_batch2, 'batch'] = adata.obs.loc[mask_batch2, 'condition'].map(condition_to_batch)

# 查看修改结果
print("\n修改后的batch分布：")
print(adata.obs['batch'].value_counts())

# 检查修改的细节
print("\n被修改的condition及其对应的新batch：")
modified_conditions = adata.obs.loc[mask_batch2, ['condition', 'batch']].drop_duplicates()
print(modified_conditions.sort_values('condition'))

print(f"\n成功修改了 {mask_batch2.sum()} 个细胞的batch信息")

# 最后检查是否还有batch2存在
batch2_remaining = adata.obs[adata.obs['batch'] == 'batch2']
if len(batch2_remaining) > 0:
    print(f"\n注意：还有 {len(batch2_remaining)} 个细胞的batch仍然是'batch2'")
    print("这些细胞的condition分布：")
    print(batch2_remaining['condition'].value_counts())
    
    # 检查这些condition是否应该在映射字典中
    batch2_conditions = set(batch2_remaining['condition'].unique())
    should_be_mapped = [c for c in batch2_conditions if c in condition_to_batch]
    if should_be_mapped:
        print(f"\n警告：以下condition本应被修改但未成功：{should_be_mapped}")

要确保存在的batch类别：{'seq2_5', 'seq2_1', 'seq2_7', 'seq2_2', 'seq2_6', 'seq2_3', 'seq2_4'}
当前的batch值：{'seq_5', 'seq_7', 'batch2', 'seq_4', 'seq_8', 'seq_3', 'seq_2', 'seq_6', 'seq_1'}

合并后的所有类别：['batch2', 'seq2_1', 'seq2_2', 'seq2_3', 'seq2_4', 'seq2_5', 'seq2_6', 'seq2_7', 'seq_1', 'seq_2', 'seq_3', 'seq_4', 'seq_5', 'seq_6', 'seq_7', 'seq_8']

重新设置类别后的batch类别：
Index(['batch2', 'seq2_1', 'seq2_2', 'seq2_3', 'seq2_4', 'seq2_5', 'seq2_6',
       'seq2_7', 'seq_1', 'seq_2', 'seq_3', 'seq_4', 'seq_5', 'seq_6', 'seq_7',
       'seq_8'],
      dtype='object')

需要修改的细胞数量：1417931

修改后的batch分布：
batch
seq2_5    283242
seq2_6    281971
seq2_7    242260
seq2_3    241055
seq2_4    224391
seq_3     223414
seq_5     212606
seq_6     196785
seq_1     194972
seq_2     161233
seq_4     154512
seq2_2    138349
seq_7      44608
seq2_1      6663
seq_8       5406
batch2         0
Name: count, dtype: int64

被修改的condition及其对应的新batch：
                                                   condition   batch
AATTCCAACCGAAGGCAAGC;AGTTCCTGTCTACAAGCACC;TGGCC...      H101  seq2_4
AAGGTACATATCGCGTTAGG;AGAAGATATAATTGGAGTAG-H102          H102  seq2_4
GACTAAGGTCAATACTCGAT-H105                               H105  seq2_4
CGATCACGATCTAAGAGTCC;GCTATGCGCTCTTGGTGGTT-H106          H106  seq2_4
CTGAGGATCCTGGACGTGAC-H108                               H108  seq2_4
...                                                      ...     ...
AGAAGCGTATGGCTTCGTCG-H76                                 H76  seq2_5
TTACTCAGACGACCTGATAA-H77                                 H77  seq2_5
CCATGCTCAGGGATATCTCC;GCTCAACTAATACAGCCGAG;GCTCG...       H80  seq2_4
CATTAATGGTGCGGTGCAGA;CCAGATATCTTCAGTACACG;CGTTC...       H88  seq2_4
ACGAGGCCATCGCCTCATCT-H89                                 H89  seq2_4

[86 rows x 2 columns]

成功修改了 1417931 个细胞的batch信息

In [52]:
adata.obs['batch'].value_counts()

batch
seq2_5    283242
seq2_6    281971
seq2_7    242260
seq2_3    241055
seq2_4    224391
seq_3     223414
seq_5     212606
seq_6     196785
seq_1     194972
seq_2     161233
seq_4     154512
seq2_2    138349
seq_7      44608
seq2_1      6663
seq_8       5406
batch2         0
Name: count, dtype: int64

In [53]:
# 查看当前的batch类别
print("删除前的batch类别：")
print(adata.obs['batch'].cat.categories)
print("\n当前的batch分布：")
print(adata.obs['batch'].value_counts())

# 删除"batch2"类别（前提是它已经没有细胞了）
if 'batch2' in adata.obs['batch'].cat.categories:
    adata.obs['batch'] = adata.obs['batch'].cat.remove_categories(['batch2'])
    print(f"\n成功删除 'batch2' 类别")
else:
    print(f"\n'batch2' 类别已不存在")

# 验证删除结果
print("\n删除后的batch类别：")
print(adata.obs['batch'].cat.categories)
print("\n删除后的batch分布：")
print(adata.obs['batch'].value_counts())

# 验证是否所有细胞都有具体的seq信息
total_cells = len(adata.obs)
cells_with_seq = sum(~adata.obs['batch'].isin(['batch2']))
print(f"\n总细胞数：{total_cells}")
print(f"有具体seq信息的细胞数：{cells_with_seq}")
print(f"比例：{cells_with_seq/total_cells*100:.2f}%")

删除前的batch类别：
Index(['batch2', 'seq2_1', 'seq2_2', 'seq2_3', 'seq2_4', 'seq2_5', 'seq2_6',
       'seq2_7', 'seq_1', 'seq_2', 'seq_3', 'seq_4', 'seq_5', 'seq_6', 'seq_7',
       'seq_8'],
      dtype='object')

当前的batch分布：
batch
seq2_5    283242
seq2_6    281971
seq2_7    242260
seq2_3    241055
seq2_4    224391
seq_3     223414
seq_5     212606
seq_6     196785
seq_1     194972
seq_2     161233
seq_4     154512
seq2_2    138349
seq_7      44608
seq2_1      6663
seq_8       5406
batch2         0
Name: count, dtype: int64

成功删除 'batch2' 类别

删除后的batch类别：
Index(['seq2_1', 'seq2_2', 'seq2_3', 'seq2_4', 'seq2_5', 'seq2_6', 'seq2_7',
       'seq_1', 'seq_2', 'seq_3', 'seq_4', 'seq_5', 'seq_6', 'seq_7', 'seq_8'],
      dtype='object')

删除后的batch分布：
batch
seq2_5    283242
seq2_6    281971
seq2_7    242260
seq2_3    241055
seq2_4    224391
seq_3     223414
seq_5     212606
seq_6     196785
seq_1     194972
seq_2     161233
seq_4     154512
seq2_2    138349
seq_7      44608
seq2_1      6663
seq_8       5406
Name: count, dtype: int64

总细胞数：2611467
有具体seq信息的细胞数：2611467
比例：100.00%

In [54]:
adata.obs['orig.ident']=adata.obs['batch']

In [ ]:
adata

In [55]:

# 1. 你已经有了adata
print(f"原始数据形状: {adata.shape}")

# 2. 设置质控参数
filter_params = {
    'min_genes': 500,      
    'max_genes': 12000,     
    'min_counts': 500,
    'max_counts': 150000,
    'max_mt': 10
}

# 3. 直接调用处理函数
adata_qc = preprocess_and_qc_analysis(adata, filter_params)

# 4. 检查结果
print(f"\n处理后的数据:")
print(f"  形状: {adata_qc.shape}")
print(f"  有UMAP: {'X_umap' in adata_qc.obsm}")
print(f"  有Leiden聚类: {'leiden' in adata_qc.obs.columns}")

# 5. 保存
adata_qc.write_h5ad("adata_qc_filtered.h5ad")
print(f"数据已保存为 adata_qc_filtered.h5ad")

原始数据形状: (2611467, 38606)
============================================================
开始质控分析流程
============================================================
初始数据形状: (2611467, 38606)
计算质控指标...
找到 13 个线粒体基因 (使用模式: ^MT-)
计算每个细胞的基因数和UMI数...
计算完成:
  - 总细胞数: 2611467
  - 总基因数: 38606
  - 线粒体基因比例范围: 0.00% - 82.87%
  - 核糖体基因比例范围: 1.51% - 67.58%
  - 每个细胞检测到的基因数范围: 194 - 17215
  - 每个细胞的UMI总数范围: 954.0 - 297076.0

保存原始counts数据...

进行质控过滤...
使用过滤参数: {'min_genes': 500, 'max_genes': 12000, 'min_counts': 500, 'max_counts': 150000, 'max_mt': 10}

各样本过滤前细胞数:
condition
H188    29101
H190    28557
H213    25409
H239    25107
H189    24926
        ...
H86      5010
H229     4023
H230     3962
H126     3850
H21      2710
Name: count, Length: 185, dtype: int64

质控过滤结果:
  - 过滤前: 2611467 个细胞
  - 过滤后: 2550159 个细胞
  - 移除: 61308 个细胞 (2.3%)

细胞被移除的主要原因:
  - 低基因数: 324 个细胞 (0.5%)
  - 高基因数: 47 个细胞 (0.1%)
  - 高UMI数: 180 个细胞 (0.3%)
  - 高线粒体比例: 61054 个细胞 (99.6%)

进行基因和细胞过滤...
  基因过滤: 38606 -> 37961 (移除 645 个基因)

进行数据标准化...
  使用counts层进行标准化

选择高变基因...

/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']
/home/liuxiaodongLab/jiangjing/miniconda3/envs/agent_new/lib/python3.10/site-packages/scanpy/preprocessing/_highly_variable_genes.py:220: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']

  计算邻居图...
  进行UMAP降维...
  进行Leiden聚类...

处理后的数据:
  形状: (2550159, 37961)
  有UMAP: True
  有Leiden聚类: True
数据已保存为 adata_qc_filtered.h5ad

In [58]:
adata_qc.obs

,condition,cell_name_in_hg38_mm10,batch,seq,time,group,orig.ident,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,total_counts_ribo,pct_counts_ribo,n_genes,leiden
CACCGTGTGTTAAGGAGAAG;GCTAAGTACTCCTATTGGTG-H4,H4,CELL12915_N2,seq_7,0,20,day20_ctl,seq_7,4132,9476.0,562.0,5.930772,1860.0,19.628534,4132,11
CGATTGATAAGCTCACCTCC-H4,H4,CELL42201_N1,seq_7,0,20,day20_ctl,seq_7,2453,7451.0,68.0,0.912629,2191.0,29.405447,2453,9
GGCAGGAGCTGTCAGGTCGT;GTGACATACATTCAGCAACT-H4,H4,CELL23261_N2,seq_7,0,20,day20_ctl,seq_7,3720,10211.0,33.0,0.323181,2412.0,23.621584,3720,11
AACCTGGTGACTTGTCTAGT;GAACCGCCTCTGAGTCTAGT;GACAGTTAGGCTTCTTCGTA;TATGCCTGATCACAAGGTCT-H4,H4,CELL350_N4,seq_7,0,20,day20_ctl,seq_7,3629,9730.0,60.0,0.616650,2204.0,22.651594,3629,12
ACCGCGGTAACAGATTCAAC;AGTCGTCCTAGATGAGAGGT-H4,H4,CELL4761_N2,seq_7,0,20,day20_ctl,seq_7,4730,16280.0,189.0,1.160934,4397.0,27.008598,4730,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CTACTACGCGATTACATAAT-H221,H221,NaN,seq2_6,1,20,Forskolin_VPA,seq2_6,1485,3406.0,10.0,0.293600,1092.0,32.061066,1485,3
GGCCTGCACAACAGTTCATT;TGCAACCGGATCGAACGCCA-H221,H221,NaN,seq2_6,1,20,Forskolin_VPA,seq2_6,2139,6024.0,42.0,0.697211,1650.0,27.390438,2139,1
AATGGAATACCCTGCGAACA;GCGACAGTGTGTGAAGTCGG-H221,H221,NaN,seq2_6,1,20,Forskolin_VPA,seq2_6,6117,31421.0,550.0,1.750422,9923.0,31.580791,6117,4
CCGATTCCAACTCACCTAAG;CGGTAGACACGCACATAGTA;CTGGCAACATGCCGTACGGT;GCCAGGTTGCGGCTCCGCTG;GTCCGTCACACAAGCTGAAG;GTCTTCGGCTTGAAGGAAGG;TATTCATATATTATGGCCAA;TTCTATCAGCCCTGATATAG-H221,H221,NaN,seq2_6,1,20,Forskolin_VPA,seq2_6,2981,8893.0,69.0,0.775891,2470.0,27.774652,2981,3
GCGTAAGTAGGGCTCCGCTG-H221,H221,NaN,seq2_6,1,20,Forskolin_VPA,seq2_6,1664,2273.0,83.0,3.651562,272.0,11.966564,1664,5